version: '3.6'
services:
  backend:
    build:
      context: ./backend/Notes.Api/Notes.Api
      dockerfile: Dockerfile
    ports:
      - 5000:80
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=Notes;Trusted_Connection=True;MultipleActiveResultSets=true;User=sa;Password=Your_password123;Integrated Security=false
    depends_on:
      - sqlserver
    restart: on-failure
    networks:
      - hc
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5004:80
    depends_on:
      - sqlserver
    networks:
      - hc
  sqlserver:
    image: microsoft/mssql-server-linux:latest
    environment:
      SA_PASSWORD: Your_password123
      ACCEPT_EULA: Y
    ports:
      - 1440:1433
    volumes:
      - dbdata:/var/opt/mssql
    networks:
      - hc

volumes:
  dbdata:

networks:
  hc:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16