version: '3.6'
services:
  backend:
    build:
      context: ./backend/Notes.Api/Notes.Api
      dockerfile: Dockerfile
    ports:
      - 62749:80
      - 44325:443
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=Notes;Trusted_Connection=True;MultipleActiveResultSets=true;User=sa;Password=Your_password123;Integrated Security=false
    depends_on:
      - sqlserver
    restart: on-failure

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5004:80
    depends_on:
      - sqlserver

  sqlserver:
    image: microsoft/mssql-server-linux:latest
    environment:
      SA_PASSWORD: Your_password123
      ACCEPT_EULA: Y
    ports:
      - 1440:1433
    volumes:
      - dbdata:/var/opt/mssql

volumes:
  dbdata: